{application_name: '__NAME__', 
domain: __DOMAIN__, 
icons_folder: icons, 
image_folder: max_resolution,
media_folder: __DATADIR__/uploads, 
root_path: __FINAL_PATH__, 
salt_code: '__SALT_CODE__',
secret: '__SECRET__',
scheme: https, 
server_description: '', 
thumb_folder: small, 
db_user: '__DB_USER__',
db_pwd: '__DB_PWD__',
db_port: '5432',
db_host: 'localhost', 
db_name: '__DB_NAME__',
email_enabled: True,
smtp_server: 'localhost',
smtp_port: 465,
smtp_login: '',
smtp_password: '',
smtp_adress: '__APP__@__DOMAIN__',
DEBUG: False,
reg: True}